// CAREN - Partner & Affiliate Fraud Detection
// Detects coordinated abuse by partners: opposite trading, fake traffic,
// commission manipulation and incentivised churn.
// Author: Alisher Beisembekov

export type AffiliateScheme =
  | 'opposite_trading'
  | 'fake_traffic'
  | 'commission_churn'
  | 'self_referral'
  | 'bonus_abuse'
  | 'incentivised_volume'
  | 'dormant_stuffing'

export interface AffiliatePartner {
  id: string
  name: string
  tier: 'platinum' | 'gold' | 'silver' | 'bronze'
  joinedAt: Date
  referredClients: number
  activeClients: number
  commissionPaid: number
  clientLifetimeValue: number
  /** Commission paid divided by value generated — above 1.0 loses money. */
  commissionRatio: number
  fraudScore: number
  schemes: AffiliateScheme[]
  status: 'healthy' | 'watchlist' | 'suspended' | 'terminated'
  narrative: { en: string; ru: string }
  escalationForecast?: { en: string; ru: string; weeksAhead: number; confidence: number }
  subAffiliates: number
  countryConcentration: number
}

export const SCHEME_META: Record<
  AffiliateScheme,
  { en: string; ru: string; descEn: string; descRu: string; severity: 'low' | 'medium' | 'high' | 'critical' }
> = {
  opposite_trading: {
    en: 'Opposite trading',
    ru: 'Встречная торговля',
    descEn: 'Paired accounts take mirrored positions so one always wins, extracting bonus or spread value with no market risk.',
    descRu: 'Парные счета открывают зеркальные позиции, поэтому одна сторона всегда выигрывает, извлекая бонус или спред без рыночного риска.',
    severity: 'critical',
  },
  fake_traffic: {
    en: 'Fake traffic',
    ru: 'Фиктивный трафик',
    descEn: 'Registrations generated by bots or incentivised click farms that never convert to genuine activity.',
    descRu: 'Регистрации, созданные ботами или мотивированными кликерами, которые никогда не превращаются в реальную активность.',
    severity: 'high',
  },
  commission_churn: {
    en: 'Commission churn',
    ru: 'Прокрутка комиссии',
    descEn: 'Clients cycled in and out to repeatedly trigger acquisition payouts on the same underlying people.',
    descRu: 'Клиенты циклически заводятся и выводятся, чтобы многократно получать выплаты за привлечение одних и тех же людей.',
    severity: 'high',
  },
  self_referral: {
    en: 'Self-referral',
    ru: 'Самореферал',
    descEn: 'Partner refers accounts they control themselves, collecting commission on their own deposits.',
    descRu: 'Партнёр приводит счета, которыми управляет сам, получая комиссию с собственных депозитов.',
    severity: 'critical',
  },
  bonus_abuse: {
    en: 'Bonus abuse',
    ru: 'Злоупотребление бонусами',
    descEn: 'Systematic extraction of welcome bonuses across many thin accounts with minimal genuine activity.',
    descRu: 'Систематическое извлечение приветственных бонусов через множество малоактивных счетов с минимальной реальной активностью.',
    severity: 'medium',
  },
  incentivised_volume: {
    en: 'Incentivised volume',
    ru: 'Накрученный объём',
    descEn: 'Artificial trading volume generated purely to hit tier thresholds, with round-trip net position near zero.',
    descRu: 'Искусственный торговый оборот, создаваемый исключительно ради достижения порогов уровня, с околонулевой итоговой позицией.',
    severity: 'high',
  },
  dormant_stuffing: {
    en: 'Dormant stuffing',
    ru: 'Набивка спящими счетами',
    descEn: 'Referral counts inflated with accounts that register, receive credit, and never transact again.',
    descRu: 'Счётчики рефералов раздуваются счетами, которые регистрируются, получают начисление и больше никогда не совершают операций.',
    severity: 'medium',
  },
}

export const TIER_LABELS: Record<AffiliatePartner['tier'], { en: string; ru: string }> = {
  platinum: { en: 'Platinum', ru: 'Платиновый' },
  gold: { en: 'Gold', ru: 'Золотой' },
  silver: { en: 'Silver', ru: 'Серебряный' },
  bronze: { en: 'Bronze', ru: 'Бронзовый' },
}

export const STATUS_LABELS: Record<AffiliatePartner['status'], { en: string; ru: string }> = {
  healthy: { en: 'Healthy', ru: 'В норме' },
  watchlist: { en: 'Watchlist', ru: 'Под наблюдением' },
  suspended: { en: 'Suspended', ru: 'Приостановлен' },
  terminated: { en: 'Terminated', ru: 'Расторгнут' },
}

const PARTNER_NAMES = [
  'NorthPeak Media', 'TradeFlow Partners', 'Apex Referral Group', 'BlueWave Digital',
  'Summit Acquisition', 'Vertex Leads', 'Crescent Affiliates', 'Ironclad Marketing',
  'Skyline Traffic', 'Meridian Partners', 'Redwood Media', 'Cobalt Growth',
]

function buildNarrative(
  schemes: AffiliateScheme[],
  ratio: number,
  clients: number,
  active: number,
  concentration: number
): { en: string; ru: string } {
  const activePct = ((active / Math.max(1, clients)) * 100).toFixed(0)

  if (schemes.length === 0) {
    return {
      en: `Performance is within normal parameters. ${activePct}% of referred clients remain active, and the commission ratio of ${ratio.toFixed(2)} sits comfortably below break-even. Geographic spread is diversified with no single country above ${concentration.toFixed(0)}% of volume.`,
      ru: `Показатели в пределах нормы. Активными остаются ${activePct}% привлечённых клиентов, а коэффициент комиссии ${ratio.toFixed(2)} уверенно ниже точки безубыточности. География диверсифицирована, ни одна страна не превышает ${concentration.toFixed(0)}% объёма.`,
    }
  }

  if (schemes.includes('opposite_trading')) {
    return {
      en: `Paired-position analysis found ${Math.floor(Math.random() * 40) + 12} account pairs opening mirrored positions within seconds of each other, consistently sized so the combined net exposure is near zero. One side always closes in profit, the other absorbs the loss, and the partner collects on both.\n\nThis is not aggressive marketing — a mirrored pair has no market thesis. It only makes sense if the objective is extracting the spread or bonus rather than trading. Commission ratio has reached ${ratio.toFixed(2)}, meaning the programme now pays out more than the referred cohort generates.`,
      ru: `Анализ парных позиций выявил ${Math.floor(Math.random() * 40) + 12} пар счетов, открывающих зеркальные позиции с разницей в секунды и подобранных так, что совокупная чистая экспозиция близка к нулю. Одна сторона всегда закрывается в прибыли, другая принимает убыток, а партнёр получает выплаты по обеим.\n\nЭто не агрессивный маркетинг: у зеркальной пары нет рыночной идеи. Она имеет смысл, только если цель — извлечение спреда или бонуса, а не торговля. Коэффициент комиссии достиг ${ratio.toFixed(2)}: программа выплачивает больше, чем генерирует привлечённая когорта.`,
    }
  }

  if (schemes.includes('fake_traffic') || schemes.includes('dormant_stuffing')) {
    return {
      en: `Only ${activePct}% of ${clients} referred clients ever transacted beyond the qualifying deposit. Registration timestamps cluster into bursts of 40–60 within single hours, and ${concentration.toFixed(0)}% originate from one country despite the partner marketing across six.\n\nGenuine acquisition campaigns do not produce that shape. Real traffic arrives spread across the day and converts unevenly; this converts identically and then stops, which is what happens when accounts are created to be counted rather than to be used.`,
      ru: `Лишь ${activePct}% из ${clients} привлечённых клиентов совершили операции сверх квалификационного депозита. Отметки времени регистрации группируются во всплески по 40–60 в пределах одного часа, и ${concentration.toFixed(0)}% приходятся на одну страну, хотя партнёр ведёт маркетинг в шести.\n\nНастоящие кампании по привлечению не дают такой картины. Реальный трафик распределён в течение суток и конвертируется неравномерно; здесь конверсия единообразна, а затем прекращается — так происходит, когда счета создают, чтобы их посчитали, а не чтобы ими пользовались.`,
    }
  }

  return {
    en: `Commission ratio of ${ratio.toFixed(2)} against ${activePct}% client retention indicates the partner is monetising acquisition events rather than customer value. ${schemes.length} distinct scheme signatures fired within the review window, and country concentration of ${concentration.toFixed(0)}% narrows the plausible explanations further.\n\nThe pattern is recoverable if addressed early: payout terms can be shifted from acquisition to retention milestones, which removes the incentive without terminating a relationship that may still be salvageable.`,
    ru: `Коэффициент комиссии ${ratio.toFixed(2)} при удержании клиентов ${activePct}% указывает, что партнёр монетизирует события привлечения, а не ценность клиента. За окно проверки сработали ${schemes.length} различных сигнатур схем, а концентрация по стране в ${concentration.toFixed(0)}% дополнительно сужает круг правдоподобных объяснений.\n\nСитуация исправима при раннем вмешательстве: условия выплат можно перенести с привлечения на этапы удержания, что снимает стимул, не расторгая отношения, которые ещё можно сохранить.`,
  }
}

function buildForecast(fraudScore: number, schemes: AffiliateScheme[]) {
  if (fraudScore < 55) return undefined

  const weeksAhead = Math.floor(Math.random() * 5) + 2
  const confidence = 0.68 + Math.random() * 0.28
  const primary = schemes[0] ? SCHEME_META[schemes[0]] : null

  return {
    en: `Trajectory analysis projects escalation within ${weeksAhead} weeks. Partners showing this combination${primary ? ` — led by ${primary.en.toLowerCase()} — ` : ' '}historically increase extraction rate sharply once they conclude the scheme is undetected. Intervening now costs a renegotiation; intervening after escalation costs the recovered balance.`,
    ru: `Анализ траектории прогнозирует эскалацию в течение ${weeksAhead} нед. Партнёры с такой комбинацией${primary ? ` — во главе со схемой «${primary.ru.toLowerCase()}» — ` : ' '}исторически резко наращивают темп извлечения, как только приходят к выводу, что схема не обнаружена. Вмешательство сейчас стоит пересмотра условий; вмешательство после эскалации стоит невозвращённого остатка.`,
    weeksAhead,
    confidence,
  }
}

export function generateAffiliatePartner(): AffiliatePartner {
  const allSchemes = Object.keys(SCHEME_META) as AffiliateScheme[]
  const isFraudulent = Math.random() < 0.42
  const schemeCount = isFraudulent ? Math.floor(Math.random() * 3) + 1 : 0

  const pool = [...allSchemes]
  const schemes: AffiliateScheme[] = []
  for (let i = 0; i < schemeCount; i++) {
    schemes.push(pool.splice(Math.floor(Math.random() * pool.length), 1)[0])
  }

  const referredClients = Math.floor(Math.random() * 400) + 30
  const activeRate = isFraudulent ? Math.random() * 0.22 + 0.03 : Math.random() * 0.4 + 0.42
  const activeClients = Math.floor(referredClients * activeRate)

  const clientLifetimeValue = Math.floor(activeClients * (Math.random() * 900 + 220))
  const commissionPaid = isFraudulent
    ? Math.floor(clientLifetimeValue * (Math.random() * 1.4 + 0.9))
    : Math.floor(clientLifetimeValue * (Math.random() * 0.35 + 0.18))

  const commissionRatio = commissionPaid / Math.max(1, clientLifetimeValue)

  const severityWeight = schemes.reduce((sum, s) => {
    const w = { low: 0.1, medium: 0.2, high: 0.3, critical: 0.4 }[SCHEME_META[s].severity]
    return sum + w
  }, 0)

  const fraudScore = Math.min(
    99,
    severityWeight * 100 + (commissionRatio > 1 ? 22 : 0) + (activeRate < 0.15 ? 18 : 0)
  )

  const status: AffiliatePartner['status'] =
    fraudScore > 82 ? 'suspended'
    : fraudScore > 58 ? 'watchlist'
    : fraudScore > 90 ? 'terminated'
    : 'healthy'

  const countryConcentration = isFraudulent
    ? Math.random() * 30 + 62
    : Math.random() * 32 + 18

  return {
    id: `AFF-${Math.floor(Math.random() * 9000 + 1000)}`,
    name: PARTNER_NAMES[Math.floor(Math.random() * PARTNER_NAMES.length)],
    tier: (['platinum', 'gold', 'silver', 'bronze'] as const)[Math.floor(Math.random() * 4)],
    joinedAt: new Date(Date.now() - Math.floor(Math.random() * 900 + 60) * 86400000),
    referredClients,
    activeClients,
    commissionPaid,
    clientLifetimeValue,
    commissionRatio,
    fraudScore,
    schemes,
    status,
    narrative: buildNarrative(schemes, commissionRatio, referredClients, activeClients, countryConcentration),
    escalationForecast: buildForecast(fraudScore, schemes),
    subAffiliates: Math.floor(Math.random() * 24),
    countryConcentration,
  }
}

export function generateAffiliatePartners(count: number = 18): AffiliatePartner[] {
  return Array.from({ length: count }, () => generateAffiliatePartner()).sort(
    (a, b) => b.fraudScore - a.fraudScore
  )
}

export function summarizeAffiliates(partners: AffiliatePartner[]) {
  const flagged = partners.filter(p => p.schemes.length > 0)

  return {
    total: partners.length,
    flagged: flagged.length,
    suspended: partners.filter(p => p.status === 'suspended' || p.status === 'terminated').length,
    // Money already paid to partners whose cohorts never justified it.
    commissionAtRisk: flagged.reduce(
      (sum, p) => sum + Math.max(0, p.commissionPaid - p.clientLifetimeValue),
      0
    ),
    totalReferred: partners.reduce((sum, p) => sum + p.referredClients, 0),
    avgCommissionRatio:
      partners.reduce((sum, p) => sum + p.commissionRatio, 0) / (partners.length || 1),
    forecastEscalations: partners.filter(p => p.escalationForecast).length,
  }
}
